### ISSUE TITLE
Remove quality-specific draw wording

### ISSUE THREAD

**Issue by KingSupernova31** [KaiGeffen/Celestial#128]
Fishing Boat and Night Vision should be changed to use the clearer "put [num] card[s] with cost [N] from your deck into your hand".

**Comment by KingSupernova31** [comment]
Note this slightly nerfs Gentle Rain

**Comment by KingSupernova31** [comment]
Kai wants Gentle Rain to count Fishing Boat, so those are going to stay "draws".

**Comment by KaiGeffen** [comment]
I went with the "put [num] card[s] with cost [N] from your deck into your hand" wording, but Gentle Rain still counts these as draws.
Do you think that's unituitive, or is it good that way?

**Comment by KingSupernova31** [comment]
I think it's a little unintuitive, but as long as the game is consistent that *any* time a card moves from the deck to the hand it counts as a draw, this rule is very easy to understand after encountering it the first time. I'd just keep an eye on user feedback, but if people aren't saying they hate it, seems fine to me.
